name: OrangeFox Build - Final

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'Manifest'
        required: true
        default: ''
        type: choice
        options:
        - https://gitlab.com/OrangeFox/sync.git
      MANIFEST_BRANCH:
        description: 'OrangeFox Branch'
        required: true
        default: '10' # Branch 11 and 12.1's lunch command doesn't work using this action builder.
        type: choice
        options:
        - 12.1
        - 11.0
        - 10.0
        - 9.0
      DEVICE_TREE:
        description: 'Custom Recovery Tree'
        required: true
        default: 'https://github.com/brigudav/android_device_xiaomi_surya_twrp'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'Specify your device path.'
        required: true
        default: 'device/xiaomi/surya'
      DEVICE_NAME:
        description: 'Specify your Device Codename.'
        required: true
        default: 'surya'
      MAKEFILE_NAME:
        description: 'Specify your twrp/omni_codename'
        required: true
        default: 'twrp_surya'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendor_boot

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v3.1.0
      
    - name: Set Current Date # For Build Date Info, currently using Australia/Sydney
      id: today
      run: |
        echo "date=$(TZ=Australia/Sydney date +%Y%m%d-%l:%M%p)" >> $GITHUB_OUTPUT
        
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
      
    - name: Build Environment
      run: |
        sudo apt install aria2 -y
        git clone https://github.com/cd-Spidey/Random.git ./buildenv
        sudo bash buildenv/setup/packages/build_env.sh
        
    - name: Install OpenJDK
      run: |
        git clone https://github.com/cd-Spidey/Random.git ./opendjk
        sudo bash opendjk/setup/packages/open_jdk.sh
        
    - name: Install Git-Repo
      run: |
        git config --global advice.detachedHead false
        git clone https://android.googlesource.com/tools/repo -b v2.29 ~/bin
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
      
    - name: Set-up Manifest
      run: |
        mkdir OrangeFox
        cd OrangeFox
        echo "workdir=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "brigudav"
        git config --global user.email "alexvl1972@hotmail.com"
        git clone https://gitlab.com/OrangeFox/sync.git
      id: pwd

    - name: Sync Manifest
      run: |
        cd sync
        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
      working-directory: OrangeFox

    - name: Clone Device Tree
      run: |
        cd fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workdir }}

    - name: Check Manifest Branch
      uses: haya14busa/action-cond@v1
      id: fox_branch
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == '11.0' || github.event.inputs.MANIFEST_BRANCH == '12.1' }}
        if_true: lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image
        if_false: lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng && mka ${{ github.event.inputs.BUILD_TARGET }}image

    - name: Building OrangeFox
      run: |
        cd fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        ccache -M 10G
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
        export LC_ALL="C"
        ${{ steps.fox_branch.outputs.value }}
      working-directory: ${{ steps.pwd.outputs.workdir }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img
          OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.zip
        name: Unofficial OrangeFox for ${{ github.event.inputs.DEVICE_NAME }}
        tag_name: ${{ github.run_id }}
        body: |
          Build: fox_${{ github.event.inputs.MANIFEST_BRANCH }} - ${{ steps.today.outputs.date }}
          Device: ${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }}
          Manifest: ${{ github.event.inputs.MANIFEST_URL }}
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
